version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
      replace-base: true
#     registries:
#       - jfrog-artifactroy

# registries:
#   jfrog-artifactroy:
#     type: "npm-registry"
#     url: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/dpndbt-pvt-repo-npm-key/"
#     token: "${{secrets.JFROG_ARTIFACTORY_TOKEN}}"
